### ISSUE TITLE
generate_cell_table fails if .tiff extensions are in supplied FOV names

### ISSUE THREAD

**Issue by HoxB8** [angelolab/ark-analysis#303]
![Screen Shot 2020-10-27 at 5 33 31 PM](https://user-images.githubusercontent.com/58482675/97376425-8caa9b80-187a-11eb-8096-465751cf0814.png)
**What are you trying to do?**
I tried to segment a multi-channel tiff.  I was able to input  the tif file and create segmented mask xarray and overlay file.   I am trying  to get the expression matrices .csv file

**What is the problem?**
I  run into an error saying: Invalid value(s) provided for fovs variable: value(s) 2020-10-24T19-45-39_Run-255_FOV1_Breast2-mid-left-2-MassCorrected-Filtered.tiff not found in segmentation labels fovs list

![Screen Shot 2020-10-27 at 5 33 31 PM](https://user-images.githubusercontent.com/58482675/97376478-acda5a80-187a-11eb-8b01-83489101c8dc.png)

**Comment by ngreenwald** [comment]
This was fixed in our most recent update. You can follow the instructions [here](https://github.com/angelolab/ark-analysis#updates) to update and that should resolve this issue

**Comment by HoxB8** [comment]
Hmm, I tried to run the update and went through everything from the beginning, but I still get the same error. 
![Uploading Screen Shot 2020-10-27 at 7.45.50 PM.png…]()

**Comment by ngreenwald** [comment]
My mistake, you're right. Looks like we missed a spot. We haven't been using the MIBITIFF format for any of this, so it hasn't been tested as thoroughly. 


The issue is that the FOV names have .tiff at the end, but the function isn't expecting .tiff, so you'll need to remove them. 

You can add this line:
`
new_fovs = io_utils.extract_delimited_names(fovs, delimiter='.tiff')
`

and then replace `fovs` with `new_fovs` when calling `generate_cell_table`
